services:
  - type: web
    name: lgs-puan-hesaplama
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lgs-database
          property: connectionString
    autoDeploy: false

databases:
  - name: lgs-database
    databaseName: lgs_production
    user: lgs_user
